
menu = [
    "WHISKEY COCKTAILS",
    "THE OLD FASHIONED 12\n\nBulleit bourbon, maraschino cherry, orange peel, sugar and Angostura bitters.",
    "SMOKED FASHIONED 13\n\nLike the classic but smoked in the glass after making for a true cowboy kick.\nBulleit bourbon, maraschino cherry, orange peel, sugar and Angostura bitters.",
    "SAZERAC 13\n\nArguably the oldest American cocktail recipe, a New Orleans classic for sure. Bulleit Rye whiskey, absinthe, Peychaud bitters, lemon peel and sugar.",
    "Coca Cola 4\n\nThe classic soft drink.",
    "GODFATHER 9\n\nJohnny Walker black label, Disaronno amaretto stirred with bitters.",
    "MANHATTAN 12\n\nServed dry, sweet or perfect.\nBulleit rye whiskey, vermouth, bitters and maraschino liqueur.",
    "LA LOUISIANE 13\n\nBulleit rye whiskey, sweet vermouth, bitters and absinthe.",
    "BOULEVARDIER 11\n\nBulleit rye whiskey, sweet vermouth, Campari.",
    "GENTLEMAN'S AGREEMENT 12\n\nLet's just agree to shake on it.\nGentleman Jack, orgeat (almond blossom) syrup, lemon juice, sparkling water to top.",
    "LYNCHBURG LEMONADE 10\n\nJack Daniel’s Tennessee straight whiskey, Bols triple sec, lemon juice, topped with Sprite.",
    "MINT JULEP 11\n\nBulleit bourbon, fresh mint and sugar over crushed ice.",
    "SMOKING GUN 11\n\n‘Il fragante delicto’, you got caught (Johnny Walker) red-handed, with Bols triple sec, lemon juice, Lillet Rouge vermouth and orgeat (almond blossom) syrup. This drink follows particularly well after having ‘The other women’.",
    "KENTUCKY MULE 11\n\nBulleit Bourbon, fresh lime, ginger beer and a dash of Angostura bitters.",
    "RUM COCKTAILS",
    "TREACLE 13\n\nDick Bradsel’s twist to the classic old fashioned.\nAppleton VX aged rum, orange peel, apple juice and bitters.",
    "CAIPIRIHNA 10\n\nCachaca, fresh lime, raw sugar.",
    "CUBAN PUSSY 11\n\n‘Say hello to my little friend!’\nPampero Blanco rum, Bols triple sec, black raspberry liqueur, orange, and apple juice.",
    "MOJITO 11\n\nHavana rum 3 yr, fresh mint, lime, sugar and a soda top.",
    "DARK N STORMY 11\n\nGosling’s navy rum, fresh lime, ginger beer and a dash of Angostura bitters.",
    "FLAMING HURRICANE 12\n\nCreated in the 1940s by the legendary bartender Pat O'Brien.\nThis super-boozy cocktail can be made a million ways, but classic style served with dark, light and overproof rum 81%, passion fruit, orange, and pineapple juice.",
    "FROZEN STRAWBERRY DAIQUIRI 11\n\nPampero white rum, fresh lime juice, sugar syrup and strawberries.",
    "CLASSIC DAIQUIRI 10\n\nPampero white rum, fresh lime juice, sugar syrup.",
    "HEMMINGWAY DAIQUIRI 11\n\nLow in sugar, high in acidity.\nPampero white rum, fresh lime juice, grapefruit juice, maraschino liqueur.",
    "NUCLEAR DAIQUIRI 13\n\nOverproof rum 81%, Green Chartreuse, Falernum, fresh lime juice and sugar syrup.",
    "ZOMBIE 15\n\nOur respect to the legendary bartender ‘Don the Beachcomber’. A blend of different aged rums: Appleton VX, navy rum, Overproof 81% & Falernum shaken with a little absinthe, fresh lime juice, grapefruit, and cinnamon Maximum of 2 per customer!",
    "FROZEN PINA COLADA 11\n\nPampero rum, coconut cream, sugar and fresh pineapple.",
    "CARIBBEAN SWIZZLE 10\n\nKoko Kanu rum, fresh lime, pineapple juice, with a touch of agave syrup.",
    "SCORPION 11\n\nPampero rum, brandy, orgeat syrup, fresh orange and lemon juice.",
    "MAI TAI 15\n\nOur favorite Tiki cocktail of all time.\nAppleton VX rum, Angostura 1919 rum, Dry Orange Curacao, orgeat syrup and fresh lime juice.",
    "JAMAICAN MULE 11\n\nSailor Jerry’s spiced rum, fresh lime, ginger beer and a dash of Orange bitters.",
    "VODKA COCKTAILS",
    "WHITE RUSSIAN 10\n\nKetel 1 vodka, Kahlua, cream.",
    "FRENCH MARTINI 11\n\nKetel 1 vodka, Chambord, pineapple juice and a splash of prosecco.",
    "LOUISIANA LADYBOY 10\n\nIt’s only a problem if you get caught.\nKetel 1 vodka, fresh strawberry, lychee, lime, and organic apple juice.",
    "BLOODY MARY 11\n\nTell us your preferred level of spice.\nKetel 1 vodka, tomato juice, lemon, Worcestershire sauce and secret spice mix.",
    "PORN STAR MARTINI 12\n\nThe most famous contemporary classic in the world.\nKetel One vodka, vanilla, Passoa, passion fruit puree and a touch of pineapple. Served with fresh passion fruit and a shot of bubbly on the side.",
    "MOSCOW MULE 10\n\nKetel One vodka, fresh lime and ginger beer.",
    "GIN COCKTAILS",
    "CARBONATED NEGRONI 10\n\nTanqueray gin, Campari, sweet vermouth.",
    "NEGRONI 10\n\nTanqueray gin, Campari, sweet vermouth.",
    "DRY MARTINI 11\n\nTanqueray gin stirred vigorously with dry vermouth and served with an olive.",
    "HANKY-PANKY 11\n\nTanqueray gin, sweet vermouth, stirred with bitters.",
    "BITTER STRIPPER 11\n\nTanqueray gin, vermouth blanc, Cointreau, Salers Gentiane.",
    "BRAMBLE 10\n\nTanqueray gin, creme de mure, fresh lemon juice and sugar syrup.",
    "GIN FO’ G’S 10\n\nWhat’s long, hard and has cum in it?\nCucumber. Muddled and shaken with Tanqueray gin, fresh lemon juice, and Bols elderflower liqueur.",
    "GINNY’S PASSION 11\n\nTanqueray gin, fresh passionfruit, ginger ale & grenadine syrup.",
    "THE OTHER WOMAN 11\n\nA super seductive drink that pairs Tanqueray gin with the dry fruitiness of Lillet Rouge vermouth, which carries on with orgeat (almond blossom) syrup, lemon and finished with Creole bitters and a subtle caress of real absinthe.",
    "RAMOS GIN FIZZ 13\n\nBe prepared to wait a little. This cocktail takes some time to prepare and we won’t compromise on that.\nTanqueray gin shaken hard (very hard) with fresh lemon, sugar, orange flower water, Rose bitters, cream, and egg white.",
    "TEQUILA COCKTAILS",
    "MARGARITA 11\n\n100% agave El Jimador reposado tequila, triple sec, fresh lime juice.",
    "CARBONATED MARGARITA 11\n\nA fizzy version of the classic with a twist.\n100% agave El Jimador reposado tequila, triple sec, fresh lime juice.",
    "B(L)ENDED MARGARITA 12\n\n100% agave El Jimador reposado tequila, Green Chartreuse, Cointreau, fresh lime juice, Hellfire bitters.",
    "TOMMY’S MARGARITA 12\n\n100% agave El Jimador reposado tequila, fresh lime juice, agave syrup",
    "MEXICAN MULE 11\n\nEl Jimador Tequila, fresh ginger & lime, ginger and a dash of Habanero bitters.",
    "BLOODY MARIA 11\n\nTell us your preferred level of spice.\n100% agave El Jimador reposado tequila, tomato juice, lemon, Worcestershire sauce and secret spice mix.",
    "LOS POLLOS HERMANOS 13\n\n‘We tried to poison you. We tried to poison you because you are an insane, degenerate piece of filth and you deserve to die.’ (Walter White - Breaking Bad)\nSmoky Mezcal, Bols apricot brandy, Agave syrup and fresh lime.",

]
